name: driver_app
description: Sürücüyü Koruyan, Yolcuyu Güvenceye Alan Teknolojik Ulaşım Altyapısı
publish_to: "none"
version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.7.3
  supabase_flutter: ^2.8.3
  google_fonts: ^6.3.2
  flutter_svg: ^2.0.9
  intl: ^0.20.2
  cached_network_image: ^3.3.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  path: ^1.9.0
  google_maps_flutter: ^2.5.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  universal_io: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
